---
title: "30 Years of Post-disturbance Recruitment in a Neotropical Forest _ Supplementary Materials"
author:
  - name: Ariane MIRABEL
    authsuperscript: 1*
  - name: Eric MARCON
    authsuperscript: 1
  - name: Bruno HERAULT
    authsuperscript: 2
affiliation:
  - affsuperscript: 1
    dptuniv: UMR EcoFoG, AgroParistech, CNRS, Cirad, INRA, Université des Antilles, Université de Guyane.
    address: >
      Campus Agronomique,
      97310 Kourou,
      France.
  - affsuperscript: 2
    dptuniv: INPHB (Institut National Polytechnique Félix Houphoüet Boigny) 
    address: Yamoussoukro, Ivory Coast
corrauthor:
    email: ariane.mirabel@ecofog.gf
    url: https://github.com/ArianeMirabel
preamble: >
  \usepackage{textcomp}
  \DeclareUnicodeCharacter{B0}{\textdegree}
  \usepackage{tabu}
  \renewenvironment{table}{\begin{table*}}{\end{table*}\ignorespacesafterend}
  \hyphenation{bio-di-ver-si-ty sap-lings post-dis-tur-bance}
  \hypersetup{draft}
  \usepackage{caption}
  \usepackage{longtable}
  \usepackage{float}
  \usepackage{booktabs}
  \captionsetup[figure]{labelformat=empty}
  \captionsetup[table]{labelformat=empty}
bibliography: references.bib
lang: english
corrauthorlabel: Corresponding author 
output: 
  bookdown::pdf_book:
    base_format: EcoFoG::article
    keep_tex: TRUE
  bookdown::gitbook: default
  bookdown::word_document2: default
---

```{r Options, echo=FALSE, message=FALSE, warning=F}
knitr::opts_chunk$set(cache=F, warning=FALSE, tidy=TRUE, tidy.opts=list(blank=FALSE, width.cutoff=40),fig.align="center")
# Installation des packages si nécessaire et chargement
Library <- function(Packages) {
  InstallAndLoad <- function(Package) {
    if (!Package %in% installed.packages()[, 1]) {install.packages(Package, repos="https://cran.rstudio.com/")}
    require(Package, character.only = TRUE)
  }
  invisible(sapply(Packages, InstallAndLoad))
}

Library("kableExtra")
#source("Scripts/GithubPages.R")
source("Scripts/DrawingTools.R")
```

\onecolumn

```{r, include=F}
library(captioner)
tables <- captioner(prefix = "Table S", auto_space = FALSE)
tables("Corrtab", "Table of pearson correlation coefficients among functional traits at species level.", display=FALSE)
tables("Splist","List of recruited species for all plots throughout the 30 years inventoried.",display=F)

figures <- captioner(prefix = "Figure S", auto_space = FALSE)
figures("BPanalysis","Breakpoint analysis of post-disturbance trajectories regarding, from left to right, taxonomic richness, taxonomic evenness, functional diversity, and taxonomic turnver of 2-years laps recuited communities. The best linear models segmented according to break points are selected based on their mean square errors. Dots are the observed trajectories, plain lines are linera model, and vertical dotted lines are the break points. Lines color correspond to initial disturbance intensity.", display = FALSE)
```


```{r Corrtab, echo=FALSE,as.is=T}
corr<-read.csv("DB/SpeciesCorrel.csv",sep=";",row.names=1)
corr[is.na(corr)]<-""

knitr::kable(corr, caption=tables("Corrtab"), longtable = FALSE, booktabs = TRUE, format="latex") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped","condensed","hold_position"), full_width = TRUE)
```

```{r BPanalysis, echo=FALSE, fig.cap=figures("BPanalysis")}
load("DB/RecruitmentPunctual");load("DB/RecruitmentPunctual_Nullmodel_Diff")
load("DB/RecruitmentPunctual_Functional");load("DB/RecruitmentPunctual_Functional_Nullmodel_Diff")
load("DB/Turnover_toInit")

load("DB/LostAGB")
norm<-(AGBloss_cor[,"AGB"]-min(AGBloss_cor[,"AGB"]))/(max(AGBloss_cor[,"AGB"])-min(AGBloss_cor[,"AGB"]))
ColorsDist <- colorRampPalette(c("darkolivegreen2","gold","orangered","darkred"))(12)[as.numeric(cut(norm, breaks = 12))]

names(RecPun)<-c("Taxonomic Richness","","Taxonomic Evenness")

#layout(rbind(c(1,1,2,2,3,3),c(1,1,2,2,3,3),c(0,0,4,4,0,0),c(0,0,4,4,0,0)))
par(mfrow=c(2,2),mar=c(3,4,2,2))

RecPun_BP <- lapply(c(1,3), function(ind){
  
  Totest <- RecPun[[ind]][AGBloss_cor[,"plot"],,"0.5"]
  
  plot(colnames(Totest),Totest[1,], ylim=c(min(Totest),max(Totest)),type="n",ylab="Diversity",xlab="year", main = names(RecPun)[ind],cex.main=0.9)
  
  breakPoints <- do.call(cbind,lapply(1:nrow(Totest),function(li){
    totest <- Totest[li,]
    x <- as.numeric(names(totest))
    
    mse <- numeric(length(x))
    
    for(i in 1:length(x)){
      piecewise1 <- lm(totest ~ x*(x < x[i]) + x*(x>=x[i]))
      mse[i] <- summary(piecewise1)$sigma
    }
    mse <- as.numeric(mse)
    
    BP <- x[which(mse==min(mse))]
    
    piecewise2 <- lm(totest ~ x*(x < BP) + x*(x > BP))
    lmBP <- summary(piecewise2)$coefficients[,"Estimate"]
    Pval <- summary(piecewise2)$fstatistic
    Pval <- round(pf(Pval[1],Pval[2],Pval[3],lower.tail=F),3)
    
    lines(x,totest,col=ColorsDist[li])
    curve((lmBP["(Intercept)"] + lmBP["x < BPTRUE"]) + (lmBP["x"]+lmBP["x:x < BPTRUE"])*x, add=T, from= x[1], to=BP,col=ColorsDist[li])
    curve((lmBP["(Intercept)"] + lmBP["x > BPTRUE"]) + lmBP["x"]*x, add=T, from=BP, to=max(x),col=ColorsDist[li])
    abline(v=BP, lty=3,col=ColorsDist[li])
    return(c(BP,min(mse),Pval))
  }))
  
  rownames(breakPoints) <- c("BP","MSEmodel","Pval")  
  colnames(breakPoints) <- rownames(Totest)
  
  return(breakPoints)
})

plot(colnames(RecPun_Fun),RecPun_Fun[1,,"0.5"],
       ylim=c(min(RecPun_Fun[,,"0.5"]),max(RecPun_Fun[,,"0.5"])),type="n",ylab="Diversity",xlab="", main = "Functional Diversity",cex.main=0.9)
RecPun_Fun_BP <- unlist(lapply(1:nrow(RecPun_Fun),function(li){
  
    totest <- RecPun_Fun[AGBloss_cor[,"plot"],,"0.5"][li,]
    x <- as.numeric(names(totest))
    
    mse <- numeric(length(x))
    
    for(i in 1:length(x)){
      piecewise1 <- lm(totest ~ x*(x < x[i]) + x*(x>=x[i]))
      mse[i] <- summary(piecewise1)$sigma
    }
    mse <- as.numeric(mse)
    
    BP <- x[which(mse==min(mse))]
    
    piecewise2 <- lm(totest ~ x*(x < BP) + x*(x > BP))
    lmBP <- summary(piecewise2)$coefficients[,"Estimate"]
    
    lines(x,totest,col=ColorsDist[li])
    curve((lmBP["(Intercept)"] + lmBP["x < BPTRUE"]) + (lmBP["x"]+lmBP["x:x < BPTRUE"])*x, add=T, from= x[1], to=BP,col=ColorsDist[li])
    curve((lmBP["(Intercept)"] + lmBP["x > BPTRUE"]) + lmBP["x"]*x, add=T, from=BP, to=max(x),col=ColorsDist[li])
    abline(v=BP, lty=3,col=ColorsDist[li])
    return(c(BP,min(mse)))
  }))

par(mar=c(3,2,2,4))
plot(colnames(Turn),Turn[1,,"0.5"],
     ylim=c(min(Turn[,,"0.5"]),max(Turn[,,"0.5"])),type="n",ylab="Diversity",xlab="", main = "Taxonomic Turnover",cex.main=0.9)
RecPun_Turn_BP <- unlist(lapply(1:nrow(Turn),function(li){
  
  totest <- Turn[AGBloss_cor[,"plot"],,"0.5"][li,]
  x <- as.numeric(names(totest))
  
  mse <- numeric(length(x))
  
  for(i in 1:length(x)){
    piecewise1 <- lm(totest ~ x*(x < x[i]) + x*(x>=x[i]))
    mse[i] <- summary(piecewise1)$sigma
  }
  mse <- as.numeric(mse)
  
  BP <- x[which(mse==min(mse))]
  
  piecewise2 <- lm(totest ~ x*(x < BP) + x*(x > BP))
  lmBP <- summary(piecewise2)$coefficients[,"Estimate"]
  
  lines(x,totest,col=ColorsDist[li])
  curve((lmBP["(Intercept)"] + lmBP["x < BPTRUE"]) + (lmBP["x"]+lmBP["x:x < BPTRUE"])*x, add=T, from= x[1], to=BP,col=ColorsDist[li])
  curve((lmBP["(Intercept)"] + lmBP["x > BPTRUE"]) + lmBP["x"]*x, add=T, from=BP, to=max(x),col=ColorsDist[li])
  abline(v=BP, lty=3,col=ColorsDist[li])
  return(c(BP,min(mse)))
}))

mtext("Years since disturbance",side=1,line=2.1)
legd<-rep(NA, 12);legd[c(1,6,12)]<-round(sort(AGBloss_cor[,"AGB"])[c(1,6,12)])
legend("right",inset=c(-0.27,0),xpd=NA,legend=rev(legd),fill=rev(ColorsDist),bty="n",title="Lost AGB\n(%)\n", y.intersp = 0.5, border=NA)

legend(x=29,y=0.05,xpd=NA,legend = "CI 95%",fill=rgb(0,0,0,alpha=0.1),border=NA,bty="n",x.intersp = 0.4)

legend(x=32,y=-0.05,xpd=NA,legend = "Breakpoint",lty=3,border=NA,bty="n",x.intersp = 0.4,cex=0.8)

```

```{r Splist, echo=FALSE,as.is=T}
load("DB/Paracou_R_Subdivided_ok")

splist<-unique(Recruitment[which(Recruitment[,"Espece"]!="Indet."),c("Famille","Genre","Espece")])
splist<-na.omit(splist[order(splist[,1],splist[,2],splist[,3]),])
rownames(splist)<-NULL

knitr::kable(splist,"latex", caption=tables("Splist"),longtable=F, booktabs = TRUE) %>%
  kableExtra::kable_styling(latex_options = c("repeat_header"), position="left") %>%
  row_spec(1:nrow(splist),italic=T) %>%
  row_spec(0,bold=T)

```

