---
title: "Notice Scripts"
author: "Ariane"
date: "27 janvier 2018"
output: html_document
bibliography: references.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Files in the *Scripts* file are annotated .R files corresponding to the production of database and subsequent plots of the whole plot article.
Files in the *DB* are the initial inventories and produced database.


### DB file

- *Alpha_Plots*: Alpha matrices for the Dirichlet sampling of the vernacular names botanical trials. 
It is a list of plot-specific matrices, following previous investigation suggesting that botanical associations should rely on local community inventories and history to minimize biases.

- *BotanyGenus*: Botanical correspondence tables to associate genuses to botanical names trialed from vernacular names.

- *BridgeOK.csv*: csv file of the Bridge dataset: 6 leaves and 2 stem traits.

- *DataLifeTraits.csv*: csv file for the Hmax and seed mass class.

- *Paracou_R_Subdivided_ok*: Formatted Paracou inventories, it contains various matrices and lists that are not all used here. 
*LivingStand_all* is the lists used here, inventories are subdivided by inventoried year and by plot.

- *RecruitmentAccum*: Richness, Shannon and Simpson diversity trajectories of the recruited communities accumulated since disturbance.

- *RecruitmentAccum_Nullmodel*: Richness, Shannon and Simpson diversity trajectories from a null model of random species sampling for the recruited communities accumulated since disturbance.

- *RecruitmentPunctual*: Richness, Shannon and Simpson diversity trajectories of the communities recruited every 3-years laps.

- *RecruitmentPunctual_Functional*: Rao diversity for the 3-years laps punstual recruitment, considering the 8 functional traits and life traits.

- *RecruitmentPunctual_Nullmodel*: Richness, Shannon and Simpson diversity trajectories from a null model of random species sampling for the communities recruited every 3-years laps.

- *Recruits_CWM*: The community abundance-weighted means of the puntually recruited communities for the 7 functional and life traits considered.

- *Turnover_toInit*: Value of abundance-based taxonomic turnover (according to @Podani2013a) of recruited communities per plot compared to the plot inventory in 1984.


### Scripts file

- *DivTaxo_trajectories.R*: Taxonomic Richness, Shannon and Simpson diversity trajectories per plot along inventoried years.

- *DrawingTools.R*: To alleviate the *Manuscript* file I defined separately the functions to draw the plots from dataset.

- *FunctionalNMDS.R*: Functional composition analysis: iterative NMDS on plots functional inventories.

- *GithubPages.R*: Script to clean the file and put .htlm files and pictures in appropriate subfiles.

- *Recruitment_NestTurn.R*: Measure of the nestedness and turnover of recruited comunities compared to plots inventories in 1984. Produces the *Turnover_toInit* file.

- *TraitsMiceFilling.R*: General functions, gap-filling of the traits database.

- *Vernacular_handle.R*: General functions, to propagate taxonomic uncertainty.

- *Recruitment_trajectories.R*: Script to generate the Richness, Shannon and Simpson diversity of plots recruitment along time. 
We considered "punctual" recruitment (trees recruited during 3-years laps) and "accumulated" recruitment (communities that were recruited since disturbance).
The null trajectories corresponding to random species sampling are also generated for the two types of recruitment.
The script produces the *RecruitmentPunctual*, *RecruitmentAccum*, *RecruitmentPunctual_Nullmodel* and *RecruitmentAccum_Nullmodel* files.

- *Recruitment_trajectories_Functional.R*: Script to generate the Rao diversity of 3-years laps punctual recruitment. 
The script produces the *RecruitmentPunctual_Functional* file.

----

`r if (knitr:::is_html_output()) '# References {-}'`
